apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: crudapp-database
type: Opaque
data:
  # echo -n "admin" | base64
  mongodb-username: YWRtaW4=
  # echo -n "password123" | base64
  mongodb-password: cGFzc3dvcmQxMjM=
  # echo -n "studentdb" | base64
  mongodb-database: c3R1ZGVudGRi